name: coverage

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Run tests and upload to codecov.io
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      
      - name: install dependencies and pytest
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt
          pip3 install pytest
          pip3 install pytest-cov
          
      - name: Generate coverage report
        run: |
          pytest --doctest-modules paminco --cov-report term --cov=paminco
      
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
